#ifndef __H5_PRIVATE_H
#define __H5_PRIVATE_H

#define H5B_CONTAINER_GRPNAME		"Block"

#define H5T_CONTAINER_GRPNAME		"Topo"
#define H5T_COORD_GRPNAME		"COORD"
#define H5T_COORD3D_DSNAME		"COORD3D"
#define H5T_COORD3D_NUM_ELEMS_DSNAME	"COORD3D_NUM_ELEMS"
#define H5T_VMESH_GRPNAME		"VOLUME_MESH"
#define H5T_TETMESH_DSNAME		"TETMESH"
#define H5T_TETMESH_NUM_ELEMS_DSNAME	"TETMESH_NUM_ELEMS"

#define H5BLOCK_GROUPNAME_BLOCK	H5B_CONTAINER_GRPNAME

#endif
