#!/bin/sh

 ./configure \
        $@ \
        --enable-parallel \
        --enable-fortran \
        --enable-tools \
        CC=cc CXX=CC FC=pgf90 \
        MPICC=cc MPICXX=CC MPIFC=ftn
sed -e 's/pgf90/ftn/g' <Makefile > newMakefile
mv newMakefile Makefile
sed -e 's/pgf90/ftn/g' <src/Makefile > newMakefile
mv newMakefile src/Makefile
sed -e 's/pgf90/ftn/g' <test/Makefile > newMakefile
mv newMakefile test/Makefile
sed -e 's/pgf90/ftn/g' <tools/Makefile > newMakefile
mv newMakefile tools/Makefile

